name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot

# Controls when the action will run (Push)
on:
  workflow_dispatch:
  push:
    branches: [ main ]

# Choose OS to build on.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

    # Install dotnet Newtonsoft.Json
    - name: Install Newtonsoft.Json
      run: dotnet add package Newtonsoft.Json
      
    # Install dotnet System.Net.Http.Json
    - name: Install System.Net.Http.Json
      run: dotnet add package System.Net.Http.Json   
      
    # Install dotnet Blazored.LocalStorage
    - name: Install Blazored.LocalStorage
      run: dotnet add package Blazored.LocalStorage  
      
    # Install OpenAI.NET
    - name: Install OpenAI.NET
      run: dotnet add package OpenAI

    # Install WebsocketManager.
    - name: Install SocketIOClient
      run: dotnet add package SocketIOClient

    # .Net Publish
    - name: Publish app
      run: dotnet publish -c Release

    # .Rewrite href Base
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: ./

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

    # Trigger Page build.
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
